namespace MonoSAMFramework.Portable.Screens.HUD.Enums
{
	public enum HUDAlignment
	{
		TOPLEFT,
		TOPRIGHT,
		BOTTOMLEFT,
		BOTTOMRIGHT,
		CENTERLEFT,
		CENTERRIGHT,
		TOPCENTER,
		BOTTOMCENTER,
		CENTER,

		ABSOLUTE,
		ABSOLUTE_BOTHCENTERED,
		ABSOLUTE_VERTCENTERED,
		ABSOLUTE_HORZCENTERED,
	}
}
