//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridDominance.DSLEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GridDominance.DSLEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Template WorldGraph   #
        ///############################
        ///
        ///scale(64)
        ///
        ///alias(0_1, {7018e8a1-6b04-447c-8972-c2c2e118fc49})
        ///alias(0_2, {9887f46b-b27e-4dba-b9f3-92a8d6ec26e6})
        ///alias(0_3, {f9f79506-f15a-47d4-abcc-afdc116b7b3c})
        ///
        ///node([0, 0], 0_1)
        ///  connect(0_2, CW)
        ///  connect(0_3, CW)
        ///
        ///node([7, 0], 0_2)
        ///  connect(0_3, CW)
        ///
        ///node([7, -7], 0_3)
        ///
        ///
        ///.
        /// </summary>
        internal static string example_graph {
            get {
                return ResourceManager.GetString("example_graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Levelfile - Example  #
        ///########################
        ///
        ///init(&quot;0-exmpl&quot;, &quot;Template&quot;, ::UUID::, 10)
        ///
        ///define(N0, 0) # Neutral
        ///define(P1, 1) # Human
        ///define(A2, 2) # PC
        ///define(A3, 3) # PC
        ///define(A4, 4) # PC
        ///
        ///define(SIZE_NORMAL, 1.0 * 96)
        ///define(CELL_W, 128)
        ///define(CELL_H, 128)
        ///
        ///scale(1, 1)
        ///
        ///########################################################################
        ///
        ///Cannon  (SIZE_NORMAL, P1, [1.5 * CELL_W, 1.5 * CELL_H])
        ///
        ///Cannon  (SIZE_NORMAL, N0, [2.5 * CELL_W, 3.5 * CELL_H])
        ///
        ///VoidWall([3.5 * CEL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string example_level {
            get {
                return ResourceManager.GetString("example_level", resourceCulture);
            }
        }
    }
}
